service: http-lambda

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'local'}
  memorySize: 1024
  deploymentPrefix: aws-lambda
  deploymentBucket: 
    name: http-lambdas-deploy

package:
  exclude:
    - node_modules/**
    - tests/

functions:
    currentTime:
        handler: backend/lambda/loan.endpoint
        events:
            - http:
                path: /loan
                method: get

custom:
  pythonRequirements:
    dockerizePip: false
  localstack:
    debug: true 
    stages:
      - local
    host: http://localhost
    autostart: true 
    lambda:
      mountCode: True
    docker:
      sudo: True